# {{@@ header() @@}} #

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
tab_spaces = {{@@ indent_width @@}}
max_width = 80

{%@@ if tabs @@%}
hard_tabs = true
{%@@ endif @@%}
