
[directory]
style="fg:{{@@ accent_color @@}} bold"
read_only = " "

[username]
show_always=true
style_user="fg:{{@@ accent_color @@}} bold"

[character]
success_symbol='\$'


[git_branch]
style="fg:{{@@ accent_color @@}} bold"
symbol = " "


[aws]
symbol = "  "
[conda]
symbol = " "
[dart]
symbol = " "
[docker_context]
symbol = " "
[elixir]
symbol = " "
[elm]
symbol = " "
[golang]
symbol = " "
[hg_branch]
symbol = " "
[java]
symbol = " "
[julia]
symbol = " "
[memory_usage]
symbol = " "
[nim]
symbol = " "
[nix_shell]
symbol = " "
[package]
symbol = " "
[perl]
symbol = " "
[php]
symbol = " "
[python]
symbol = " "
[ruby]
symbol = " "
[rust]
symbol = " "
[scala]
symbol = " "
[shlvl]
symbol = " "
[swift]
symbol = "ﯣ "
