# {{@@ header() @@}}
#  _  __     _
# | |/ /__ _| | _____  _   _ _ __   ___
# | ' // _` | |/ / _ \| | | | '_ \ / _ \
# | . \ (_| |   < (_) | |_| | | | |  __/
# |_|\_\__,_|_|\_\___/ \__,_|_| |_|\___|


source "%val{config}/rc/plug.kak"
source "%val{config}/rc/keys.kak"
source "%val{config}/rc/usermode.kak"
source "%val{config}/rc/hooks.kak"
source "%val{config}/rc/colors.kak"
