# {{@@ header() @@}}
#  _  __     _
# | |/ /__ _| | _____  _   _ _ __   ___
# | ' // _` | |/ / _ \| | | | '_ \ / _ \
# | . \ (_| |   < (_) | |_| | | | |  __/
# |_|\_\__,_|_|\_\___/ \__,_|_| |_|\___|


source "%val{config}/plug.kak"
source "%val{config}/keys.kak"
source "%val{config}/usermode.kak"
source "%val{config}/hooks.kak"
source "%val{config}/colors.kak"
