#!/bin/sh

set -x

projdir="${HOME}/Projects"

user="{{@@ mail.personal.user @@}}"
host="git.{{@@ mail.personal.mail @@}}"

#{%@@ if False @@%}#
user="$USER"
host="github.com"
#{%@@ endif @@%}#
git -C "$projdir" rev-parse >/dev/null &&
    exit 0

git clone "ssh://git@${host}:${user}/projects" "$projdir"

cd "$projdir"

git submodule update --init --recursive
