#!/bin/sh

set -e

read files

git filter-branch -f  --index-filter \
    "git rm --force --cached --ignore-unmatch $files" \
     -- --all

rm -Rf .git/refs/original && \
    git reflog expire --expire=now --all && \
    git gc --aggressive && \
    git prune
