#!/bin/sh

if ! pidof gpg-agent
then
    gpg-agent --daemon
    sleep 5s
fi

KEYGRIP=$(cat "$HOME/.pam-gnupg")

sudo cat /etc/.passwd |
    base64 -d |
    /usr/lib/gnupg/gpg-preset-passphrase --preset "$KEYGRIP"
