#!/bin/sh

gpg-connect-agent reloadagent /bye

PATH="$PATH:/usr/lib:/usr/libexec"
keygrip=$(cat "$HOME/.pam-gnupg")

echo '{{@@ main_password @@}}' |
    base64 -d |
    gpg-preset-passphrase --preset "$keygrip"
