#!/bin/sh

my_path="$1"
my_name="$2"
my_user="$3"
my_host="$4"
my_pass="$5"

cat <<EOF
set realname = "$my_name"
set from = "${my_name}@${my_host}"
set smtp_url = 'smtps://${my_user}@${my_host}'
set smtp_pass = '$my_pass'

# set Mailboxes
set folder = ~/.local/share/mail/${my_path}/
set spoolfile = "+INBOX"
set record = "+Sent"
set postponed = "+Drafts"
set trash = "+Trash"

unmailboxes *

mailboxes \
    `echo ~/.local/share/mail/${my_path}/INBOX*` \
    "=Sent" \
    "=Drafts" \
    "=Trash" \

EOF
