#!/bin/sh

pkill -9 swayidle

exec swayidle -w \
   before-sleep 'pkill caffeinated; swaylock -f' \
       after-resume 'pkill kanshi; kanshi' \
   timeout 360 'pkill caffeinated; swaylock -f' \
       resume 'pkill kanshi; kanshi' \
   timeout 1800 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"; pkill kanshi; kanshi' \
