#!/bin/sh
set -e

if test -z "$SWAYSOCK" && pidof gnome-shell > /dev/null
then
    exit 0
fi

test -z "$XDG_RUNTIME_DIR" &&
    export XDG_RUNTIME_DIR=/run/user/$(id -u)

die() {
    test "$?" = 0 ||
        notify-send "Failed to sync mail" "try unlocking your gpg key"
}
# trap die EXIT

{%@@ for name in mail | reverse @@%}
    mkdir -p "$HOME/.local/share/mail/{{@@ name @@}}/"
{%@@ endfor @@%}

getnew() {
    cd "$HOME/.local/share/mail/" >/dev/null

    find */INBOX*/new -type f |
        sed -E '/Duolingo|LBRY/d' |
        wc -l
}

OLD=$(getnew)

if test "$1" = "update" && ! pidof mbsync; then
    if ! ping -c3 {{@@ mail.personal.mail @@}} > /dev/null
    then
        exit 0
    fi
    mbsync -a
fi

NEW=$(getnew)

if test "$NEW" -gt "$OLD"; then
    notify-send " New E-Mails!"
fi

echo $NEW | sed 's/^0$//'

# vim:ft=sh
