#!/bin/sh
set -e

test "$XDG_CURRENT_DESKTOP" = "gnome" &&
    exit 0

test -z "$XDG_RUNTIME_DIR" &&
    export XDG_RUNTIME_DIR=/run/user/$(id -u)

getnew(){
    pushd "$HOME/.local/share/mail/" > /dev/null

    find INBOX*/new -type f |
        wc -l

    popd > /dev/null
}

OLD=$(getnew)

[ "$1" = "update" ] &&
    mbsync -a

NEW=$(getnew)

[ "$NEW" -gt "$OLD" ] &&
    notify-send " New E-Mails!"

echo $NEW | sed 's/^0$//'

[ "$(ps -o comm= $PPID)" != "waybar" ] &&
pidof waybar>/dev/null &&
    pkill -SIGRTMIN+4 waybar


# vim:ft=sh
