#!/bin/bash


RED_ON="$(pidof redshift)"

if test -n "$RED_ON";then
    pkill redshift
fi

grim -g "$(slurp -b aabbcc00 -p)" - |
    convert - txt:- |
    grep -oE '#[0-9A-Fa-f]{6}' |
    wl-copy -n

notify-send "$(wl-paste)" "Copied to clipboard"

test -n "$RED_ON"  && redshift &> /dev/null &
