#!/bin/sh

set -e

command -v makepkg &>/dev/null ||
    exit 1

install_pikaur() {
    PIKDIR="$HOME/.cache/pikaur/build/pikaur"
    test -d "$PIKDIR" ||
        git clone \
            https://aur.archlinux.org/pikaur.git \
            "$PIKDIR"

    cd "$PIKDIR"

    makepkg -si --noconfirm --needed
}

command -v pikaur &>/dev/null ||
    install_pikaur

cd "$HOME/.local/share/metapkg/"

source ./PKGBUILD

all_pkgs=$(pacman -Sql)
init_system=$(readlink /bin/init | cut -d- -f1)

pikaur \
    --pkgbuild \
    --install \
    --rebuild \
    --noconfirm \
    --keepbuilddep ||
    for depend in ${depends[@]}; do
        pacman -S --needed --noconfirm $depend
    done

for depend in ${depends[@]}; do
    if printf "%s\n" $all_pkgs |
        grep "^$depend-$init_system\$"; then
        sudo pacman -S \
            --needed \
            --noconfirm \
            "$depend-$init_system"
    fi
done
