#!/bin/sh

f=$(mktemp)
clean(){
    rm "$f"
}
trap clean EXIT

cat > "$f"

if test $(tput lines) -lt $(wc -l < "$f")
then
    cat "$f" |
    kak -e '
        map global normal q :q<ret>;
        rmhl global/number-lines;
        set global scrolloff 10,0;
    '
else
    cat "$f"
fi
