#!/bin/sh

# {%@@ if launcher == "wofi" @@%} #
which wofi &> /dev/null &&
    exec wofi \
        --show drun \
        --allow-images \
        --no-actions \
        --prompt 'Iniciar: ' \

# {%@@ else @@%} #
which bmenu &> /dev/null &&
    exec bmenu run
# {%@@ endif @@%} #

notify-send "Error" "Launcher program missing"
