#!/bin/fish

test -n "$SWAYSOCK" && swaymsg fullscreen off > /dev/null

# {%@@ if launcher == "wofi" @@%} #
    command -qs wofi &&
    exec wofi \
        --show drun \
        --allow-images \
        --no-actions \
        --prompt 'Iniciar: ' \

# {%@@ else @@%} #
    command -qs bmenu &&
    exec bmenu run
# {%@@ endif @@%} #

notify-send "Error" "Launcher program missing"
