#!/bin/sh

opts="Fone\nSpeaker\nHDMI"
out=$(printf $opts | wdmenu -p "Output: ")
vol=$(pamixer --get-volume)

case "$out" in
    Fone)
        pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
        pactl set-sink-port @DEFAULT_SINK@ analog-output-headphones
        ;;
    Speaker)
        pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
        pactl set-sink-port @DEFAULT_SINK@ analog-output-speaker
        ;;
    HDMI)
        pactl set-card-profile 0 output:hdmi-stereo+input:analog-stereo
        ;;
esac

pamixer --set-volume "$vol"
