#!/bin/fish

function get_vol
    math (env LC_ALL=c pactl list sinks |
            string replace -fr '.*Volume:.*front-left:.*(.*?)%.*front-right:.*(.*?)%.*' '($1 + $2)/2')
end

function p_round
   math "round( $argv[2] / $argv[1] ) * $argv[1]"
end

function volume -a "vol_diff"
    set cur_vol (math (get_vol) $vol_diff)
    echo cur (get_vol)
    while test $cur_vol -gt 100
        set cur_vol (math $cur_vol - 5)
    end

    echo $cur_vol
    set new_vol (p_round 5 $cur_vol)
    echo $new_vol

    pactl set-sink-volume @DEFAULT_SINK@ $new_vol%
end

switch $argv[1]
    case vol
        volume $argv[2..-1]
    case *
        echo não
end
