#!/bin/sh

test "$1" = "-e" && shift
# {%@@ if terminal == "alacritty" @@%} #
    command -v alacritty > /dev/null &&
    {
        test $# -gt 0 &&
            exec alacritty -e $@ ||
            exec alacritty
    }
# {%@@ elif terminal == "kitty" @@%} #
    command -v kitty > /dev/null &&
        exec kitty -- $@
# {%@@ endif @@%} #

notify-send "Error" "Terminal program missing"
