#!/bin/sh

# {%@@ if launcher == "wofi" @@%} #
command -v wofi > /dev/null &&
    exec wofi -d $@
# {%@@ else @@%} #
command -v bemenu > /dev/null &&
    exec bmenu $@
# {%@@ endif @@%} #

notify-send "Error" "Launcher program missing"
