#!/usr/bin/fish

if not command -v qemu-system-x86_64 > /dev/null
    echo qemu not installed
    exit 1
end

# -cdrom ~/Downloads/win10.iso \
# -boot order=d \
# -nic none\
# -usb -device usb-tablet \
# -vga qxl                                                    \

qemu-system-x86_64                                              \
    -enable-kvm                                                 \
    -m 2G                                                       \
    -cpu host                                                   \
    -smp (nproc)                                                \
    -display sdl,gl=on                                          \
    -audiodev pa,id=snd0                                    \
    -device ich9-intel-hda \
    -device hda-output,audiodev=snd0\
    -drive file="$HOME/.local/share/windows10.img",format=raw
