config:
  backup: true
  banner: false
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  default_actions:
  - notify
profiles:
  i15:
    dotfiles:
    - nvim
    - sway
    - fish
    - mako
    - waybar
    - kitty
    - qutebrowser
    - lesskey
    - scripts
    - wofi
    - ranger
    - zathura
    - wallpapers
    - mime
    - fusuma
    - alacritty
    - mpd
    variables:
      key:
        left: h
        down: t
        up: n
        right: s
        next: l
      font:
        mono: Fira Code
        interface: Inter
      use:
        playerctl: false
      color:
        accent: '#D9534F'
        bg: '#202020'
        bg_light: '#303030'
        bg_dark: '#191919'
        txt: '#ffffff'
        nontxt: '#252525'
        normal:
          black: '#555555'
          red: '#D54E53'
          green: '#B9CA4A'
          yellow: '#E6C547'
          blue: '#7AA6DA'
          magenta: '#C397D8'
          cyan: '#70C0BA'
          white: '#EAEAEA'
      bar: waybar
      bar_pos: top
dotfiles:
  nvim:
    src: config/nvim
    dst: ~/.config/nvim
    actions:
      - vimplug
      - notify
  sway:
    src: config/sway.conf
    dst: ~/.config/sway/config
    actions:
      - reload_sway
      - notify
  fish:
    src: config/fish.fish
    dst: ~/.config/fish/config.fish
  mako:
    src: config/mako.conf
    dst: ~/.config/mako/config
    actions:
    - makoreload
    - notify
  waybar:
    src: config/waybar
    dst: ~/.config/waybar
  kitty:
    src: config/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  qutebrowser:
    src: config/qutebrowser.py
    dst: ~/.config/qutebrowser/config.py
  lesskey:
    src: lesskey
    dst: ~/.lesskey
    actions:
    - lesskey
    - notify
  scripts:
    src: scripts
    dst: ~/.local/bin
  wofi:
    src: config/wofi
    dst: ~/.config/wofi
  ranger:
    src: config/ranger
    dst: ~/.config/ranger
  zathura:
    src: config/zathura.conf
    dst: ~/.config/zathura/zathurarc
  wallpapers:
    src: wallpapers
    dst: ~/.local/share/wallpapers
  mime:
    src: mime/
    dst: ~/
  fusuma:
    src: config/fusuma.yml
    dst: ~/.config/fusuma/config.yml
  alacritty:
    src: config/alacritty.yml
    dst: ~/.config/alacritty.yml
  mpd:
    src: config/mpd.conf
    dst: ~/.config/mpd/mpd.conf
actions:
  notify: notify-send "Updating dotfiles"
  makoreload: makoctl reload
  lesskey: lesskey
  reload_sway: swaymsg reload
  vimplug: >
    nvim
    +PlugUpgrade
    +PlugClean!
    +PlugInstall
    +PlugUpdate
    +qall
    &> /dev/null
    & disown
