#      _       _      _
#   __| | ___ | |_ __| |_ __ ___  _ __
#  / _` |/ _ \| __/ _` | '__/ _ \| '_ \
# | (_| | (_) | || (_| | | | (_) | |_) |
#  \__,_|\___/ \__\__,_|_|  \___/| .__/
#                                |_|

###############################################################
config:
###############################################################

    backup: false
    banner: false
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    dotpath: .


###############################################################
actions:
###############################################################

    greetd_install: sudo chown -R greeter:greeter /etc/greetd/
    grub_install: update-grub
    locale_install: locale-gen
    groups_install: sh ~/.local/share/groups
    pacman_install: |
        pacman-key --init
        pacman-key --populate
    sv_update: |
        {%@@ set key =  "{} _dotfile_key {}".format('{{@@', '@@}}') @@%}
        sv restart {{@@ key @@}} ||
        rc-service {{@@ key @@}} restart


###############################################################
dotfiles:
###############################################################

    greetd:
        src: greetd
        dst: /etc/greetd
        actions:
        - greetd_install

    elogind:
        src: elogind.conf
        dst: /etc/elogind/logind.conf
        actions:
        - sv_update

    grub:
        src: grub
        dst: /etc/default/grub
        actions:
        - grub_install

    pacman:
        src: pacman.conf
        dst: /etc/pacman.conf
        actions:
        - pacman_install

    locale:
        src: locale.gen
        dst: /etc/locale.gen
        actions:
        - locale_install


    groups:
        src: groups
        dst: ~/.local/share/groups
        actions:
        - groups_install


###############################################################
profiles:
###############################################################
    main:
        dotfiles:
        - ALL
