#      _       _      _
#   __| | ___ | |_ __| |_ __ ___  _ __
#  / _` |/ _ \| __/ _` | '__/ _ \| '_ \
# | (_| | (_) | || (_| | | | (_) | |_) |
#  \__,_|\___/ \__\__,_|_|  \___/| .__/
#                                |_|

###############################################################
config:
###############################################################

    backup: false
    banner: false
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    dotpath: .
    func_file:
    - "../funcs.py"
    filter_file:
    - "../funcs.py"
    # import_configs:
    # - "../config.yaml"


# ###############################################################
# variables:
# ###############################################################

#     plymouth: true
#     zram: false
#     filesystem:
#         partitions:
#             "/": /mnt/btrfs-root
#             "/@home": /home
#             "/@sql": /var/lib/mysql
#             "/@swap": /swap

###############################################################
dynvariables:
###############################################################

    # phisical_uuid: sudo blkid /dev/sda2 -s UUID -o value
    # decrypted_uuid: sudo blkid /dev/mapper/main -s UUID -o value
    # boot_uuid: sudo blkid /dev/sda1 -s UUID -o value
    # root_subvol: echo "/@$(lsb_release -i | cut -f 2)-root"
    nproc: nproc
    # memory_size: env LC_ALL=C free -b | awk '/^Mem:/ {print $2}'

###############################################################
actions:
###############################################################

    greetd_install: _greetd_install
    grub_install: update-grub
    locale_install: locale-gen
    pacman_install: |
        pacman-key --init
        pacman-key --populate
    sv_update: |
        sv restart "{{@@ '_dotfile_key' @@}}" ||
        rc-service "{{@@ '_dotfile_key' @@}}" restart

    create_subvolumes: _create-subvolumes
    create_swapfile: _create-swapfile
    mount_partitions: mount -a
    dbus_uuidgen: dbus-uuidgen --ensure
    sysctl_apply: sysctl -a
    mkinitcpio: mkinitcpio -P
    start_services: >
        _runit_config "{{@@ _dotfile_abs_dst @@}}"
        apache
        cronie
        dbus
        dhcpcd
        docker
        earlyoom
        elogind
        greetd
        iwd
        bluetoothd
        mariadb
        preload
        syslog-ng
        tlp


###############################################################
dotfiles:
###############################################################

    runit_sv:
        src: runit_sv
        dst: /etc/runit/sv

    greetd:
        src: greetd
        dst: /etc/greetd
        actions:
        - greetd_install

    elogind:
        src: elogind.conf
        dst: /etc/elogind/logind.conf
        actions:
        - dbus_uuidgen

    # grub:
    #     src: grub
    #     dst: /etc/default/grub
    #     actions:
    #     - grub_install

    # mkinitcpio:
    #     src: mkinitcpio.conf
    #     dst: /etc/mkinitcpio.conf
    #     actions:
    #     - mkinitcpio

    pacman:
        src: pacman.conf
        dst: /etc/pacman.conf
        actions:
        - pacman_install

    bluez:
        src: bluetooth.conf
        dst: /etc/bluetooth/main.conf

    locale:
        src: locale.gen
        dst: /etc/locale.gen
        actions:
        - locale_install

    # fstab:
    #     src: fstab
    #     dst: /etc/fstab
    #     actions:
    #     - create_subvolumes
    #     - create_swapfile
    #     - mount_partitions

    sysctl:
        src: sysctl
        dst: /etc/sysctl.d
        actions:
        - sysctl_apply

    # zram:
    #     src: zram
    #     dst: /etc/

    # earlyoom:
    #     src: earlyoom
    #     dst: /etc/default/earlyoom

    services:
        src: runit_sv
        dst: /etc/runit/sv
        actions:
        - start_services


###############################################################
profiles:
###############################################################
    main:
        dotfiles:
        - ALL
