#      _       _      _
#   __| | ___ | |_ __| |_ __ ___  _ __
#  / _` |/ _ \| __/ _` | '__/ _ \| '_ \
# | (_| | (_) | || (_| | | | (_) | |_) |
#  \__,_|\___/ \__\__,_|_|  \___/| .__/
#                                |_|

###############################################################
config:
###############################################################

    backup: false
    banner: false
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    dotpath: .


###############################################################
actions:
###############################################################

    greetd_install: |
        sudo chown -R greeter:greeter /etc/greetd/


###############################################################
dotfiles: # Just a bunch of paths and action mappings
###############################################################

    greetd:
        src: greetd
        dst: ~/greetd
        actions:
        - greetd_install


###############################################################
profiles:
###############################################################
    main:
        dotfiles:
        - ALL

