#      _       _      _
#   __| | ___ | |_ __| |_ __ ___  _ __
#  / _` |/ _ \| __/ _` | '__/ _ \| '_ \
# | (_| | (_) | || (_| | | | (_) | |_) |
#  \__,_|\___/ \__\__,_|_|  \___/| .__/
#                                |_|

###############################################################
config:
###############################################################

    backup: false
    banner: false
    keepdot: false
    link_dotfile_default: nolink
    link_on_import: nolink
    dotpath: .
    func_file:
    - "{{@@ _dotdrop_dotpath @@}}/../funcs.py"
    filter_file:
    - "{{@@ _dotdrop_dotpath @@}}/../funcs.py"


###############################################################
actions:
###############################################################

    greetd_install: _greetd_install
    grub_install: update-grub
    locale_install: locale-gen
    groups_install: sh ~/.local/share/groups
    pacman_install: |
        pacman-key --init
        pacman-key --populate
    sv_update: |
        sv restart "{{@@ '_dotfile_key' | var @@}}" ||
        rc-service "{{@@ '_dotfile_key' | var @@}}" restart

    create_subvolumes: _create-subvolumes
    create_swapfile: _create-swapfile
    mount_partitions: mount -a
    dbus_uuidgen: dbus-uuidgen --ensure
    passwd: chmod 600 /etc/.passwd
    sysctl_apply: sysctl -a
    mkinitcpio: mkinitcpio -P
    start_services: >
        _runit_config "{{@@ _dotfile_abs_dst @@}}"
        apache
        cronie
        dbus
        dhcpcd
        docker
        earlyoom
        elogind
        greetd
        iwd
        mariadb
        preload
        syslog-ng


###############################################################
dotfiles:
###############################################################

    runit_sv:
        src: runit_sv
        dst: /etc/runit/sv

    greetd:
        src: greetd
        dst: /etc/greetd
        actions:
        - greetd_install

    passwd:
        src: passwd
        dst: /etc/.passwd
        actions:
        - passwd

    elogind:
        src: elogind.conf
        dst: /etc/elogind/logind.conf
        actions:
        - sv_update
        - dbus_uuidgen

    grub:
        src: grub
        dst: /etc/default/grub
        actions:
        - grub_install

    mkinitcpio:
        src: mkinitcpio.conf
        dst: /etc/mkinitcpio.conf
        actions:
        - mkinitcpio

    pacman:
        src: pacman.conf
        dst: /etc/pacman.conf
        actions:
        - pacman_install

    locale:
        src: locale.gen
        dst: /etc/locale.gen
        actions:
        - locale_install

    fstab:
        src: fstab
        dst: /etc/fstab
        actions:
        - create_subvolumes
        - create_swapfile
        - mount_partitions

    sysctl:
        src: sysctl
        dst: /etc/sysctl.d
        actions:
        - sysctl_apply

    zram:
        src: zram
        dst: /etc/

    earlyoom:
        src: earlyoom
        dst: /etc/default/earlyoom

    groups:
        src: groups
        dst: ~/.local/share/groups
        actions:
        - groups_install

    usr_scripts:
        src: "{{@@ env['HOME'] @@}}/.local/bin"
        dst: /usr/local/bin

    services:
        src: runit_sv
        dst: /etc/runit/sv
        actions:
        - start_services


###############################################################
profiles:
###############################################################
    main:
        dotfiles:
        - ALL
