swipe:
  3:
    left:
      command: 'swaymsg workspace prev'
    right:
      command: 'swaymsg workspace next'
    up:
      command: 'swaymsg fullscreen toggle'
    down:
        command: 'wofi -S drun -ip"Iniciar: "'
# pinch:
#   in:
#     command: 'xdotool key ctrl+shift+plus'
#   out:
#     command: 'xdotool key ctrl+minus'

# threshold:
#   swipe: 1
#   # pinch: 0.2

# interval:
#   swipe: 0.5
#   # pinch: 0.2
